apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: devops-app
spec:
  replicas: 2          # Kubernetes runs 2 copies — if one crashes, the other keeps serving
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: todo-app
          image: docker-app:latest      # built locally with docker compose build
          imagePullPolicy: Never        # use local image, don't pull from Docker Hub
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          livenessProbe:               # K8s restarts container if /health returns error
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:              # K8s only sends traffic when app is ready
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
