apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: devops-app
spec:
  type: NodePort          # exposes nginx on a port you can access from your browser
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080     # access app at http://$(minikube ip):30080
